name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: set version
      run: |
        echo "#define BUILD_VERSION ($GITHUB_RUN_NUMBER)" > src/version.h
        echo "#define BUILD_SERVER (\"github\")" >> src/version.h
    - name: Build FW
      run: pio run
    - name: Build SPIFFS
      run: pio run --target buildfs --environment esp32dev
    - name: store artifacts
      run: |
        mkdir out
        cp .pio/build/esp32dev/partitions.bin out/bbl_gh_partitions-$GITHUB_RUN_NUMBER.bin
        cp .pio/build/esp32dev/firmware.bin out/bbl_gh_firmware-$GITHUB_RUN_NUMBER.bin
        cp .pio/build/esp32dev/spiffs.bin out/bbl_gh_spiffs-$GITHUB_RUN_NUMBER.bin
        cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/sdk/bin/bootloader_dio_40m.bin out/bbl_gh_bootloader-$GITHUB_RUN_NUMBER.bin
        cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin out/bbl_gh_boot_app0-$GITHUB_RUN_NUMBER.bin
      uses: actions/upload-artifact@v2
      with:
        name: firmware-${{ github.run_number }}
        path: out/