name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build FW
      run: pio run
    - name: Build SPIFFS
      run: pio run --target buildfs --environment esp32dev
    - name: Copy artefacts to "out" dir
      run: |
        echo "version $GITHUB_RUN_NUMBER"
        mkdir out
        cp .pio/build/esp32dev/partitions.bin out/bbl_partitions-$GITHUB_RUN_NUMBER.bin
        cp .pio/build/esp32dev/firmware.bin out/bbl_firmware-$GITHUB_RUN_NUMBER.bin
        cp .pio/build/esp32dev/spiffs.bin out/bbl_spiffs-$GITHUB_RUN_NUMBER.bin
        cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/sdk/bin/bootloader_dio_40m.bin out/bbl_bootloader-$GITHUB_RUN_NUMBER.bin
        cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin out/bbl_boot_app0-$GITHUB_RUN_NUMBER.bin
        ls out
    - uses: actions/upload-artifact@v2
      with:
        name: firmware-$GITHUB_RUN_NUMBER
        path: out/