name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: set version
      run: |
        echo "#define BUILD_VERSION ($GITHUB_RUN_NUMBER)" > src/version.h
        echo "#define BUILD_SERVER (\"github\")" >> src/version.h
        echo "#define BUILD_COMMIT_SHA (\"$GITHUB_SHA\")" >> src/version.h
        echo "#define CONFIG_WIFI_SSID (\"${{ secrets.DEFAULT_WIFI_SSID }}\")" > src/credentials.h
        echo "#define CONFIG_WIFI_PASSWORD (\"${{ secrets.DEFAULT_WIFI_PASSWORD }}\")" >> src/credentials.h
    - name: Build FW
      run: pio run
    - name: Build SPIFFS
      run: pio run --target buildfs --environment esp32dev
    - name: copy artifacts
      run: |
        mkdir out
        cp .pio/build/esp32dev/partitions.bin out/bbl_gh_partitions-$GITHUB_RUN_NUMBER.bin
        cp .pio/build/esp32dev/firmware.bin out/bbl_gh_firmware-$GITHUB_RUN_NUMBER.bin
        cp .pio/build/esp32dev/spiffs.bin out/bbl_gh_spiffs-$GITHUB_RUN_NUMBER.bin
        cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/sdk/bin/bootloader_dio_40m.bin out/bbl_gh_bootloader-$GITHUB_RUN_NUMBER.bin
        cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin out/bbl_gh_boot_app0-$GITHUB_RUN_NUMBER.bin
    - name: store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware-${{ github.run_number }}
        path: out/
    - name: upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}        
        SOURCE_DIR: out
        DEST_DIR: fw_${{ github.run_number }}